### ISSUE TITLE
Why is default drop disabled?

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-it/nfldap_reload#1]
https://github.com/mozilla-it/nfldap_reload/blob/master/nfldap_reload.py#L126 comments out the drop and the loop starting at https://github.com/mozilla-it/nfldap_reload/blob/master/nfldap_reload.py#L122 has it's own drop.

This doesn't seem to work as intended, i.e., some traffic can still go through.

**Comment by jdow** [comment]
this was fixed a long time ago.
